environment:
  AUTH0_AUDIENCE: '${AUTH0_AUDIENCE}'
  AUTH0_JWKS_URI: '${AUTH0_JWKS_URI}'
  LOG_DESTINATIONS: '[{"logtail":{"token":"${LOG_TAIL_SOURCE_TOKEN}"}}]'
  LOG_LEVEL: '${LOG_LEVEL}'
packages:
  - name: portfolio
    shared: false
    functions:
      - name: search
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: view
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: create
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: update
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: contribute
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: follower
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: member
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
  - name: account-balance
    shared: false
    functions:
      - name: deposit
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: view
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
  - name: stock
    functions:
      - name: details
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: search
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: transaction
        limits:
          timeout: 30000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
