packages:
  - name: portfolio
    shared: false
    functions:
      - name: search
        limits:
          timeout: 150000
          memory: 1024
        binary: false
        runtime: 'python:default'
        web: true
        main: 'search'