packages:
  - name: portfolio
    shared: false
    environment:
      AUTH0_AUDIENCE: '${AUTH0_AUDIENCE}'
      AUTH0_JWKS_URI: '${AUTH0_JWKS_URI}'
      LOG_DESTINATIONS: '[{"logtail":{"token":"${LOG_TAIL_SOURCE_TOKEN}"}}]'
    functions:
      - name: search
        limits:
          timeout: 3000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: view
        limits:
          timeout: 3000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: create
        limits:
          timeout: 5000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: update
        limits:
          timeout: 5000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: contribute
        limits:
          timeout: 5000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: follower
        limits:
          timeout: 5000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
      - name: member
        limits:
          timeout: 5000
          memory: 128
        binary: false
        runtime: 'python:default'
        web: true
        main: ''
