packages:
  - name: '${APP_PACKAGE_NAME}'
    shared: false
    functions:
      - name: theezy-trader
        limits:
          timeout: 150000
          memory: 1024
        binary: false
        runtime: 'python:default'
        web: true
        main: ''