name: digitalocean-deploy

on:
  push:
    branches: [ "sandbox" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    name: Deploy to DigitalOcean
    steps:
      - uses: actions/checkout@v4
        with:
          path: app/packages/theezy/theezy-trader-core-platform
          ref: ${{ github.event.ref }}
        name: Checkout repository
      - name: List files in checkout directory
        run: ls -al app/packages/theezy/theezy-trader-core-platform
      - name: Move Project configuration to Application
        run: mv app/packages/theezy/theezy-trader-core-platform/project.yml app
      - name: Remove git and github related folders
        run: rm -rf app/packages/theezy/theezy-trader-core-platform/.git app/packages/theezy/theezy-trader-core-platform/.github
      - name: Create configuration directory
        run: mkdir -p ${{ github.workspace }}/config/doctl
      - name: Install doctl cli
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install DigitalOcean deployment configuration
        run: doctl serverless install
      - name: Connect to DigitalOcean Functions namespace
        run: doctl serverless connect ${{ vars.DIGITALOCEAN_FUNCTIONS_NAMESPACE }}
      - name: Deploy to DigitalOcean
        run: doctl serverless deploy app --remote-build
        env:
          APP_PACKAGE_NAME: ${{ vars.DIGITALOCEAN_FUNCTIONS_APP }}